-- migrate:up

create extension if not exists "uuid-ossp";

create schema hotel;

create table hotel.hotels
(
    id uuid primary key default uuid_generate_v4(),
    name text not null,
    address text not null,
    rating float default 0,
    constraint unique_hotel unique (name, address),
    constraint rating_valid check (rating >= 0 and rating <= 5)
);

create table hotel.services
(
    id uuid primary key default uuid_generate_v4(),
    title text not null,
    description text not null,
    constraint unique_service unique (title)
);

create table hotel.room
(
    id uuid primary key default uuid_generate_v4(),
    class text not null,
    floor int not null,
    number int not null,
    hotel_id uuid references hotel.hotels,
    constraint unique_room unique (number, hotel_id),
    constraint unsigned_floor_number check (floor > 0 and number > 0),
    constraint class_valid check (class in ('люкс', 'делюкс', 'студия',
    'стандарт', 'семейный', 'комфорт', 'эконом', 'сьют', 'апартаменты', 'премиум'))
);

create table hotel.hotel_service
(
    hotel_id uuid references hotel.hotels,
    service_id uuid references hotel.services,
    primary key (hotel_id, service_id)
);

insert into hotel.hotels(name, address, rating)
values ('Омега Сириус', 'Олимпийский пр. 3', '4.9'),
       ('Дельта Сириус', 'Триумфальный пр. 1', '4.9'),
       ('Сочи парк', 'континетальный пр. 6', '4.7'),
       ('Альфа Сириус', 'Парусная 21', '5.0'),
       ('Гамма Сириус', 'Воскресенская 8', '4.7'),
       ('Бархатные сезоны', 'Диброва 8', '4.6'),
       ('Редиссон', '65 лет победы 50', '5.0'),
       ('Мантера', 'Голубая 1А', '5.0');

insert into hotel.room(class, floor, number, hotel_id)
values ('люкс', 1, 101, (select id from hotel.hotels where name = 'Мантера')),
       ('стандарт', 1, 102, (select id from hotel.hotels where name = 'Мантера')),
       ('стандарт', 1, 103, (select id from hotel.hotels where name = 'Мантера')),
       ('эконом', 1, 104, (select id from hotel.hotels where name = 'Мантера')),
       ('люкс', 1, 105, (select id from hotel.hotels where name = 'Мантера')),
       ('студия', 1, 106, (select id from hotel.hotels where name = 'Мантера')),
       ('апартаменты', 1, 107, (select id from hotel.hotels where name = 'Мантера')),
       ('премиум', 1, 108, (select id from hotel.hotels where name = 'Мантера')),
       ('семейный', 1, 109, (select id from hotel.hotels where name = 'Мантера')),
       ('эконом', 1, 110, (select id from hotel.hotels where name = 'Мантера')),
       ('люкс', 2, 201, (select id from hotel.hotels where name = 'Мантера')),
       ('премиум', 2, 202, (select id from hotel.hotels where name = 'Мантера')),
       ('делюкс', 2, 203, (select id from hotel.hotels where name = 'Мантера')),
       ('люкс', 2, 204, (select id from hotel.hotels where name = 'Мантера')),
       ('стандарт', 2, 205, (select id from hotel.hotels where name = 'Мантера')),
       ('премиум', 2, 206, (select id from hotel.hotels where name = 'Мантера')),
       ('студия', 2, 207, (select id from hotel.hotels where name = 'Мантера')),
       ('сьют', 2, 208, (select id from hotel.hotels where name = 'Мантера')),
       ('апартаменты', 2, 209, (select id from hotel.hotels where name = 'Мантера')),
       ('эконом', 2, 210, (select id from hotel.hotels where name = 'Мантера')),
       ('семейный', 3, 211, (select id from hotel.hotels where name = 'Мантера')),
       ('апартаменты', 3, 301, (select id from hotel.hotels where name = 'Мантера')),
       ('стандарт', 3, 302, (select id from hotel.hotels where name = 'Мантера')),
       ('стандарт', 3, 303, (select id from hotel.hotels where name = 'Мантера')),
       ('делюкс', 3, 304, (select id from hotel.hotels where name = 'Мантера')),
       ('студия', 3, 305, (select id from hotel.hotels where name = 'Мантера')),
       ('комфорт', 3, 306, (select id from hotel.hotels where name = 'Мантера')),
       ('апартаменты', 3, 307, (select id from hotel.hotels where name = 'Мантера')),
       ('люкс', 3, 308, (select id from hotel.hotels where name = 'Мантера')),
       ('сьют', 3, 309, (select id from hotel.hotels where name = 'Мантера')),
       ('стандарт', 3, 310, (select id from hotel.hotels where name = 'Мантера')),

       ('люкс', 1, 101, (select id from hotel.hotels where name = 'Редиссон')),
       ('стандарт', 1, 102, (select id from hotel.hotels where name = 'Редиссон')),
       ('стандарт', 1, 103, (select id from hotel.hotels where name = 'Редиссон')),
       ('эконом', 1, 104, (select id from hotel.hotels where name = 'Редиссон')),
       ('люкс', 1, 105, (select id from hotel.hotels where name = 'Редиссон')),
       ('студия', 1, 106, (select id from hotel.hotels where name = 'Редиссон')),
       ('апартаменты', 1, 107, (select id from hotel.hotels where name = 'Редиссон')),
       ('премиум', 1, 108, (select id from hotel.hotels where name = 'Редиссон')),
       ('люкс', 1, 109, (select id from hotel.hotels where name = 'Редиссон')),
       ('эконом', 1, 110, (select id from hotel.hotels where name = 'Редиссон')),
       ('люкс', 2, 201, (select id from hotel.hotels where name = 'Редиссон')),
       ('семейный', 2, 202, (select id from hotel.hotels where name = 'Редиссон')),
       ('стандарт', 2, 203, (select id from hotel.hotels where name = 'Редиссон')),
       ('делюкс', 2, 204, (select id from hotel.hotels where name = 'Редиссон')),
       ('стандарт', 2, 205, (select id from hotel.hotels where name = 'Редиссон')),
       ('премиум', 2, 206, (select id from hotel.hotels where name = 'Редиссон')),
       ('студия', 2, 207, (select id from hotel.hotels where name = 'Редиссон')),
       ('сьют', 2, 208, (select id from hotel.hotels where name = 'Редиссон')),
       ('апартаменты', 2, 209, (select id from hotel.hotels where name = 'Редиссон')),
       ('эконом', 2, 210, (select id from hotel.hotels where name = 'Редиссон')),
       ('люкс', 3, 211, (select id from hotel.hotels where name = 'Редиссон')),
       ('апартаменты', 3, 301, (select id from hotel.hotels where name = 'Редиссон')),
       ('стандарт', 3, 302, (select id from hotel.hotels where name = 'Редиссон')),
       ('стандарт', 3, 303, (select id from hotel.hotels where name = 'Редиссон')),
       ('сьют', 3, 304, (select id from hotel.hotels where name = 'Редиссон')),
       ('студия', 3, 305, (select id from hotel.hotels where name = 'Редиссон')),
       ('комфорт', 3, 306, (select id from hotel.hotels where name = 'Редиссон')),
       ('апартаменты', 3, 307, (select id from hotel.hotels where name = 'Редиссон')),
       ('люкс', 3, 308, (select id from hotel.hotels where name = 'Редиссон')),
       ('сьют', 3, 309, (select id from hotel.hotels where name = 'Редиссон')),
       ('стандарт', 3, 310, (select id from hotel.hotels where name = 'Редиссон')),

       ('люкс', 1, 101, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('семейный', 1, 102, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('стандарт', 1, 103, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('эконом', 1, 104, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('люкс', 1, 105, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('студия', 1, 106, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('апартаменты', 1, 107, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('премиум', 1, 108, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('люкс', 1, 109, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('эконом', 1, 110, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('люкс', 2, 201, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('делюкс', 2, 202, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('стандарт', 2, 203, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('люкс', 2, 204, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('стандарт', 2, 205, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('премиум', 2, 206, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('студия', 2, 207, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('сьют', 2, 208, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('апартаменты', 2, 209, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('эконом', 2, 210, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('люкс', 3, 211, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('апартаменты', 3, 301, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('семейный', 3, 302, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('стандарт', 3, 303, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('сьют', 3, 304, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('студия', 3, 305, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('комфорт', 3, 306, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('апартаменты', 3, 307, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('люкс', 3, 308, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('сьют', 3, 309, (select id from hotel.hotels where name = 'Бархатные сезоны')),
       ('стандарт', 3, 310, (select id from hotel.hotels where name = 'Бархатные сезоны')),

       ('люкс', 1, 101, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('стандарт', 1, 102, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('стандарт', 1, 103, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('эконом', 1, 104, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('люкс', 1, 105, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('студия', 1, 106, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('апартаменты', 1, 107, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('премиум', 1, 108, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('люкс', 1, 109, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('эконом', 1, 110, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('люкс', 2, 201, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('премиум', 2, 202, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('стандарт', 2, 203, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('люкс', 2, 204, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('стандарт', 2, 205, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('семейный', 2, 206, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('студия', 2, 207, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('сьют', 2, 208, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('апартаменты', 2, 209, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('эконом', 2, 210, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('люкс', 3, 211, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('апартаменты', 3, 301, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('стандарт', 3, 302, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('стандарт', 3, 303, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('сьют', 3, 304, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('семейный', 3, 305, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('комфорт', 3, 306, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('апартаменты', 3, 307, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('люкс', 3, 308, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('сьют', 3, 309, (select id from hotel.hotels where name = 'Омега Сириус')),
       ('стандарт', 3, 310, (select id from hotel.hotels where name = 'Омега Сириус')),

       ('люкс', 1, 101, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('стандарт', 1, 102, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('стандарт', 1, 103, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('эконом', 1, 104, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('люкс', 1, 105, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('студия', 1, 106, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('апартаменты', 1, 107, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('премиум', 1, 108, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('люкс', 1, 109, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('эконом', 1, 110, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('люкс', 2, 201, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('премиум', 2, 202, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('семейный', 2, 203, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('люкс', 2, 204, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('стандарт', 2, 205, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('премиум', 2, 206, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('студия', 2, 207, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('сьют', 2, 208, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('апартаменты', 2, 209, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('эконом', 2, 210, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('люкс', 3, 211, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('апартаменты', 3, 301, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('стандарт', 3, 302, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('стандарт', 3, 303, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('семейный', 3, 304, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('студия', 3, 305, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('комфорт', 3, 306, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('апартаменты', 3, 307, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('люкс', 3, 308, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('сьют', 3, 309, (select id from hotel.hotels where name = 'Дельта Сириус')),
       ('стандарт', 3, 310, (select id from hotel.hotels where name = 'Дельта Сириус')),

       ('люкс', 1, 101, (select id from hotel.hotels where name = 'Сочи парк')),
       ('стандарт', 1, 102, (select id from hotel.hotels where name = 'Сочи парк')),
       ('стандарт', 1, 103, (select id from hotel.hotels where name = 'Сочи парк')),
       ('эконом', 1, 104, (select id from hotel.hotels where name = 'Сочи парк')),
       ('люкс', 1, 105, (select id from hotel.hotels where name = 'Сочи парк')),
       ('студия', 1, 106, (select id from hotel.hotels where name = 'Сочи парк')),
       ('апартаменты', 1, 107, (select id from hotel.hotels where name = 'Сочи парк')),
       ('премиум', 1, 108, (select id from hotel.hotels where name = 'Сочи парк')),
       ('люкс', 1, 109, (select id from hotel.hotels where name = 'Сочи парк')),
       ('эконом', 1, 110, (select id from hotel.hotels where name = 'Сочи парк')),
       ('люкс', 2, 201, (select id from hotel.hotels where name = 'Сочи парк')),
       ('премиум', 2, 202, (select id from hotel.hotels where name = 'Сочи парк')),
       ('стандарт', 2, 203, (select id from hotel.hotels where name = 'Сочи парк')),
       ('люкс', 2, 204, (select id from hotel.hotels where name = 'Сочи парк')),
       ('стандарт', 2, 205, (select id from hotel.hotels where name = 'Сочи парк')),
       ('премиум', 2, 206, (select id from hotel.hotels where name = 'Сочи парк')),
       ('студия', 2, 207, (select id from hotel.hotels where name = 'Сочи парк')),
       ('сьют', 2, 208, (select id from hotel.hotels where name = 'Сочи парк')),
       ('апартаменты', 2, 209, (select id from hotel.hotels where name = 'Сочи парк')),
       ('эконом', 2, 210, (select id from hotel.hotels where name = 'Сочи парк')),
       ('люкс', 3, 211, (select id from hotel.hotels where name = 'Сочи парк')),
       ('апартаменты', 3, 301, (select id from hotel.hotels where name = 'Сочи парк')),
       ('стандарт', 3, 302, (select id from hotel.hotels where name = 'Сочи парк')),
       ('стандарт', 3, 303, (select id from hotel.hotels where name = 'Сочи парк')),
       ('сьют', 3, 304, (select id from hotel.hotels where name = 'Сочи парк')),
       ('студия', 3, 305, (select id from hotel.hotels where name = 'Сочи парк')),
       ('комфорт', 3, 306, (select id from hotel.hotels where name = 'Сочи парк')),
       ('апартаменты', 3, 307, (select id from hotel.hotels where name = 'Сочи парк')),
       ('люкс', 3, 308, (select id from hotel.hotels where name = 'Сочи парк')),
       ('сьют', 3, 309, (select id from hotel.hotels where name = 'Сочи парк')),
       ('стандарт', 3, 310, (select id from hotel.hotels where name = 'Сочи парк')),

       ('люкс', 1, 101, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('стандарт', 1, 102, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('стандарт', 1, 103, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('эконом', 1, 104, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('люкс', 1, 105, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('студия', 1, 106, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('апартаменты', 1, 107, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('премиум', 1, 108, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('люкс', 1, 109, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('эконом', 1, 110, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('люкс', 2, 201, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('премиум', 2, 202, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('стандарт', 2, 203, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('люкс', 2, 204, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('стандарт', 2, 205, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('премиум', 2, 206, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('студия', 2, 207, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('сьют', 2, 208, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('апартаменты', 2, 209, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('эконом', 2, 210, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('люкс', 3, 211, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('апартаменты', 3, 301, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('стандарт', 3, 302, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('стандарт', 3, 303, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('сьют', 3, 304, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('студия', 3, 305, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('комфорт', 3, 306, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('апартаменты', 3, 307, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('люкс', 3, 308, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('сьют', 3, 309, (select id from hotel.hotels where name = 'Альфа Сириус')),
       ('стандарт', 3, 310, (select id from hotel.hotels where name = 'Альфа Сириус')),

       ('люкс', 1, 101, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('стандарт', 1, 102, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('стандарт', 1, 103, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('эконом', 1, 104, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('люкс', 1, 105, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('студия', 1, 106, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('апартаменты', 1, 107, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('премиум', 1, 108, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('люкс', 1, 109, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('эконом', 1, 110, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('люкс', 2, 201, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('премиум', 2, 202, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('стандарт', 2, 203, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('люкс', 2, 204, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('стандарт', 2, 205, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('премиум', 2, 206, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('студия', 2, 207, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('сьют', 2, 208, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('апартаменты', 2, 209, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('эконом', 2, 210, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('люкс', 3, 211, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('апартаменты', 3, 301, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('стандарт', 3, 302, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('стандарт', 3, 303, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('сьют', 3, 304, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('студия', 3, 305, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('комфорт', 3, 306, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('апартаменты', 3, 307, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('люкс', 3, 308, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('сьют', 3, 309, (select id from hotel.hotels where name = 'Гамма Сириус')),
       ('стандарт', 3, 310, (select id from hotel.hotels where name = 'Гамма Сириус'));

insert into hotel.services(title, description)
values ('Питание', 'завтрак + обед в формате шведского стола. Питание включается в стоимость проживания.'),
       ('Доставка еды в номер', 'доставка готовых блюд ресторанного уровня прямо до двери гостя.
       Заказ можно сделать, позвонив по телефону на ресепшен.'),
       ('Доступ в спа и спортзал', 'Платный или бесплатный доступ в спа-центр и тренажёрный зал при их
       наличии предоставляет гостиница в соответсвии со своей политикой'),
       ('Услуги прачечной', 'Если вам нужно постирать или погладить вещь, и вы не хотите делать это самостоятельно,
       то можно обратиться в прачечную при отеле. Вещь приведут в порядок за несколько дней, а иногда и быстрее.'),
       ('Автостоянка и аренда автомобиля', 'Размещение личного транспорта на парковке при отеле тоже не всегда входит
       в стоимость проживания. Оплатить парковку, как правило, можно на месте при заселении.
       Также через ресепшен отеля при необходимости можно арендовать автомобиль.'),
       ('Побудка к определенному времени', 'если вам нужно рано вставать, то вы можете заказать эту услугу на ресепшен'),
       ('Вызов скорой помощи', 'Вызов скорой помощи через ресепшен');

insert into hotel.hotel_service(hotel_id, service_id)
values
    ((select id from hotel.hotels where name = 'Мантера'),
     (select id from hotel.services where title = 'Питание')),
    ((select id from hotel.hotels where name = 'Мантера'),
     (select id from hotel.services where title = 'Доставка еды в номер')),
    ((select id from hotel.hotels where name = 'Мантера'),
     (select id from hotel.services where title = 'Доступ в спа и спортзал')),
    ((select id from hotel.hotels where name = 'Мантера'),
     (select id from hotel.services where title = 'Услуги прачечной')),
    ((select id from hotel.hotels where name = 'Мантера'),
     (select id from hotel.services where title = 'Автостоянка и аренда автомобиля')),
    ((select id from hotel.hotels where name = 'Мантера'),
     (select id from hotel.services where title = 'Вызов скорой помощи')),
    ((select id from hotel.hotels where name = 'Мантера'),
     (select id from hotel.services where title = 'Побудка к определенному времени')),

    ((select id from hotel.hotels where name = 'Редиссон'),
     (select id from hotel.services where title = 'Питание')),
    ((select id from hotel.hotels where name = 'Редиссон'),
     (select id from hotel.services where title = 'Доставка еды в номер')),
    ((select id from hotel.hotels where name = 'Редиссон'),
     (select id from hotel.services where title = 'Доступ в спа и спортзал')),
    ((select id from hotel.hotels where name = 'Редиссон'),
     (select id from hotel.services where title = 'Услуги прачечной')),
    ((select id from hotel.hotels where name = 'Редиссон'),
     (select id from hotel.services where title = 'Автостоянка и аренда автомобиля')),
    ((select id from hotel.hotels where name = 'Редиссон'),
     (select id from hotel.services where title = 'Вызов скорой помощи')),
    ((select id from hotel.hotels where name = 'Редиссон'),
     (select id from hotel.services where title = 'Побудка к определенному времени')),

    ((select id from hotel.hotels where name = 'Бархатные сезоны'),
     (select id from hotel.services where title = 'Питание')),
    ((select id from hotel.hotels where name = 'Бархатные сезоны'),
     (select id from hotel.services where title = 'Доставка еды в номер')),
    ((select id from hotel.hotels where name = 'Бархатные сезоны'),
     (select id from hotel.services where title = 'Доступ в спа и спортзал')),
    ((select id from hotel.hotels where name = 'Бархатные сезоны'),
     (select id from hotel.services where title = 'Услуги прачечной')),
    ((select id from hotel.hotels where name = 'Бархатные сезоны'),
     (select id from hotel.services where title = 'Автостоянка и аренда автомобиля')),
    ((select id from hotel.hotels where name = 'Бархатные сезоны'),
     (select id from hotel.services where title = 'Вызов скорой помощи')),
    ((select id from hotel.hotels where name = 'Бархатные сезоны'),
     (select id from hotel.services where title = 'Побудка к определенному времени')),

    ((select id from hotel.hotels where name = 'Гамма Сириус'),
     (select id from hotel.services where title = 'Питание')),
    ((select id from hotel.hotels where name = 'Гамма Сириус'),
     (select id from hotel.services where title = 'Доставка еды в номер')),
    ((select id from hotel.hotels where name = 'Гамма Сириус'),
     (select id from hotel.services where title = 'Доступ в спа и спортзал')),
    ((select id from hotel.hotels where name = 'Гамма Сириус'),
     (select id from hotel.services where title = 'Услуги прачечной')),
    ((select id from hotel.hotels where name = 'Гамма Сириус'),
     (select id from hotel.services where title = 'Автостоянка и аренда автомобиля')),
    ((select id from hotel.hotels where name = 'Гамма Сириус'),
     (select id from hotel.services where title = 'Вызов скорой помощи')),
    ((select id from hotel.hotels where name = 'Гамма Сириус'),
     (select id from hotel.services where title = 'Побудка к определенному времени')),

    ((select id from hotel.hotels where name = 'Альфа Сириус'),
     (select id from hotel.services where title = 'Питание')),
    ((select id from hotel.hotels where name = 'Альфа Сириус'),
     (select id from hotel.services where title = 'Доставка еды в номер')),
    ((select id from hotel.hotels where name = 'Альфа Сириус'),
     (select id from hotel.services where title = 'Доступ в спа и спортзал')),
    ((select id from hotel.hotels where name = 'Альфа Сириус'),
     (select id from hotel.services where title = 'Услуги прачечной')),
    ((select id from hotel.hotels where name = 'Альфа Сириус'),
     (select id from hotel.services where title = 'Автостоянка и аренда автомобиля')),
    ((select id from hotel.hotels where name = 'Альфа Сириус'),
     (select id from hotel.services where title = 'Вызов скорой помощи')),
    ((select id from hotel.hotels where name = 'Альфа Сириус'),
     (select id from hotel.services where title = 'Побудка к определенному времени')),

    ((select id from hotel.hotels where name = 'Сочи парк'),
     (select id from hotel.services where title = 'Питание')),
    ((select id from hotel.hotels where name = 'Сочи парк'),
     (select id from hotel.services where title = 'Доставка еды в номер')),
    ((select id from hotel.hotels where name = 'Сочи парк'),
     (select id from hotel.services where title = 'Доступ в спа и спортзал')),
    ((select id from hotel.hotels where name = 'Сочи парк'),
     (select id from hotel.services where title = 'Услуги прачечной')),
    ((select id from hotel.hotels where name = 'Сочи парк'),
     (select id from hotel.services where title = 'Автостоянка и аренда автомобиля')),
    ((select id from hotel.hotels where name = 'Сочи парк'),
     (select id from hotel.services where title = 'Вызов скорой помощи')),
    ((select id from hotel.hotels where name = 'Сочи парк'),
     (select id from hotel.services where title = 'Побудка к определенному времени')),

    ((select id from hotel.hotels where name = 'Дельта Сириус'),
     (select id from hotel.services where title = 'Питание')),
    ((select id from hotel.hotels where name = 'Дельта Сириус'),
     (select id from hotel.services where title = 'Доставка еды в номер')),
    ((select id from hotel.hotels where name = 'Дельта Сириус'),
     (select id from hotel.services where title = 'Доступ в спа и спортзал')),
    ((select id from hotel.hotels where name = 'Дельта Сириус'),
     (select id from hotel.services where title = 'Услуги прачечной')),
    ((select id from hotel.hotels where name = 'Дельта Сириус'),
     (select id from hotel.services where title = 'Автостоянка и аренда автомобиля')),
    ((select id from hotel.hotels where name = 'Дельта Сириус'),
     (select id from hotel.services where title = 'Вызов скорой помощи')),
    ((select id from hotel.hotels where name = 'Дельта Сириус'),
     (select id from hotel.services where title = 'Побудка к определенному времени')),

    ((select id from hotel.hotels where name = 'Омега Сириус'),
     (select id from hotel.services where title = 'Питание')),
    ((select id from hotel.hotels where name = 'Омега Сириус'),
     (select id from hotel.services where title = 'Доставка еды в номер')),
    ((select id from hotel.hotels where name = 'Омега Сириус'),
     (select id from hotel.services where title = 'Доступ в спа и спортзал')),
    ((select id from hotel.hotels where name = 'Омега Сириус'),
     (select id from hotel.services where title = 'Услуги прачечной')),
    ((select id from hotel.hotels where name = 'Омега Сириус'),
     (select id from hotel.services where title = 'Автостоянка и аренда автомобиля')),
    ((select id from hotel.hotels where name = 'Омега Сириус'),
     (select id from hotel.services where title = 'Вызов скорой помощи')),
    ((select id from hotel.hotels where name = 'Омега Сириус'),
     (select id from hotel.services where title = 'Побудка к определенному времени'));

-- migrate:down